spring.application.name=Political-Pioneer
server.port=

spring.datasource.url=jdbc:postgresql://
spring.datasource.username=neondb_owner
server.shutdown=graceful

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=fakepassworddd

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Setting dd-auto=create will restart the database values/clear the db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




