spring.application.name=Political-Pioneer
server.port=8444

spring.datasource.url=


spring.datasource.username=



spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=fakepassword

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true




