spring.application.name=Political-Pioneer
server.port=8107

spring.datasource.url=jdbc:postgresql://ep-floral-hat-ayf5nfdo-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require


spring.datasource.username=



spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


